### ISSUE TITLE
Approximately 220 Plans Appear on Single Page 

### ISSUE THREAD

**Issue by ssantaana** [spiritcapsule/islandora_drupal_subsite_aegaron#14]
* http://drupaldev.aegaron.ucla.edu/search/plans

There are approximately 220 plans (images) showing up on a single page, should there be some sort of paging involved?

**Comment by spiritcapsule** [comment]
There are several ways to browse / search the data. The default search page just shows everything by default and can be filtered by entering a location in the search box. For most users, the way it is now is preferred. If that presents an accessibility problem, what's the guideline that it violates?

**Comment by ssantaana** [comment]
I don't know if it violates any guidelines. But from a usability standpoint, that is a lot of data to listen to on one page. At least if it were on different pages, they can bookmark the page and come back later to browse again when they have ore time.

**Comment by spiritcapsule** [comment]
we don't expect users to sit and read or listen to the whole page. it's there to say, hey there's lots of data here, and apparently it conveys that concept pretty well. the search to filter the list is easy to find at the top of the page. and the browse page has the plans categorized by both location and time period if a user does not want to see the whole list at once.
